name: iOS Test on PR

on:
  pull_request:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    name: Run iOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Carthage dependencies
        run: carthage bootstrap --platform iOS

      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '14.2'  # Adjust the Xcode version as needed

      - name: Build and test iOS project
        run: xcodebuild test -workspace Mex.xcworkspace -scheme MexTests -destination 'platform=iOS Simulator,name=iPhone 13'  # Adjust the project/workspace name, scheme, and destination as needed

