name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run MexTests
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        xcodebuild -project Mex.xcodeproj -scheme Mex -destination 'platform=iOS Simulator,name=iPhone 14' '-only-testing:MexTests' test


    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/reports # Or the path where your test results are generated
