name: Run Tests on PR

on:
  pull_request:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.5'  # Adjust the Swift version as needed

      - name: Install dependencies
        run: swift package resolve

      - name: Run tests
        run: swift test
